version: "3.9"
   
services:
  digital_web:
    build: ./app
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - digital_postgres

  digital_postgres:
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - digital_web

volumes:
  postgres_data:
  static_volume:
