# Generated by Django 4.0.6 on 2022-08-02 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fe', models.FloatField(default=0, verbose_name='Железо')),
                ('si', models.FloatField(default=0, verbose_name='Кремний')),
                ('al', models.FloatField(default=0, verbose_name='Алюминий')),
                ('ca', models.FloatField(default=0, verbose_name='Кальций')),
                ('s', models.FloatField(default=0, verbose_name='Сера')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата добавления данных')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Показатели',
            },
        ),
    ]
